### ISSUE TITLE
Suggestion: Allow specifying the path to KaTeX

### ISSUE THREAD

**Issue by sbrl** [BenjaminHoegh/parsedown-extreme#13]
I'm a bit unsure on how the inbuilt KaTeX support works. I assume ParsedownExtreme finds KaTeX and renders it to an inline SVG or something, but how do I tell it where to find KaTeX? I might have installed it to somewhere that isn't in my `PATH` environment variable.

Come to think about it, I could ask the same about Mermaid.

I'm confused.

**Comment by BenjaminHoegh** [comment]
This is something I can add for sure if you like.

By default you install KaTeX as there [guide](https://katex.org/docs/browser.html) You are welcome to install it in any path you like you just have to remember to link to the resource using `<script>` in your HTML

**Comment by BenjaminHoegh** [comment]
it do, but KaTeX doesn't, so when enable it in ParsedownExtreme you tell the code to look out for LaTeX code so it doesn't manipulate with it

**Comment by sbrl** [comment]
Ah, I see. Thanks for the clarification :-)
